baseurl: "https://pages.ghe.rakuten-it.com/boaz-yaniv/tech-blog-demo"  # Include trailing slash
languageCode: "en-us"
title: "Rakuten Engineering Blog"
pygmentsstyle: 'monokai'

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
